outputOrError: FIX: Correct line condition (after 8aec982)
Literal line numbers only work on their own; need to compare against NR in complex conditionals.
Apparently hasn't caused any real issues.

(This corrects commit 8aec98264636a02ba41384153068f9fb0e1f740a)

System-info: Ubuntu 24.04.3 LTS, x86_64
Platform-info: bash 5.2.21(1)-release, Bats 1.10.0