outputOrError: Documentation: Implement usage help
Unfortunately, awk itself will grab the -h and --help arguments, so only the -? will reach our code; therefore, add --man and --usage alternatives.